---
#-----------------------------------------------------------------------------#
# ansible-yunohost allows to deploy Yunohost using Ansible                    #
# Copyright 2021-present Lydra https://www.lydra.fr/                          #
#                                                                             #
# this program is free software: you can redistribute it and/or modify        #
# it under the terms of the GNU General Public License as published by        #
# the Free Software Foundation, either version 3 of the License, or           #
# (at your option) any later version.                                         #
#                                                                             #
# this program is distributed in the hope that it will be useful,             #
# but WITHOUT ANY WARRANTY; without even the implied warranty of              #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the                #
# GNU General Public License for more details.                                #
#                                                                             #
# You should have received a copy of the GNU General Public License           #
# along with this program. If not, see <http://www.gnu.org/licenses/>.        #
#                                                                             #
#-----------------------------------------------------------------------------#

# Variables for local YunoHost backups
ynh_backup:
  scheduled:                          False

# Variables for YunoHost BorgBackup
ynh_borg_backup_scheduled:            False
m3nu_ansible_role_borgbackup_version: "v0.9.4"
borg_source_directories:
  - "/home/yunohost.backup"
borg_repository:                      "/data/backup/borg_repository"
borg_init_command:                    "borgmatic init -c /etc/borgmatic/{{ borgmatic_config_name }} -e repokey --syslog-verbosity 1"
borg_archive_name_format:             "'{hostname}-yunohost-live-data-{now:%Y-%m-%d-%H%M%S}'"
ynh_borg_backup_remote_repo:          False

# Variables for YunoHost Restic
# https://github.com/roles-ansible/ansible_role_restic
ynh_restic_backup_scheduled:          False
do1jlr_restic_version:                "v0.7.1"
restic_version:                       "0.14.0"
restic_schedule_type:                 "cronjob"
restic_keep_time:                     "0y1m0d0h"
